<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hiphops"
    nsURI="http://md.kth.se/hiphops" nsPrefix="hiphops">
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//DescribedClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" upperBound="-1"
        eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simulationX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazards" upperBound="-1"
        eType="#//Hazard"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//DescribedClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lines" upperBound="-1"
        eType="#//Line" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//DescribedClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementation" eType="#//Implementation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impalternatives" upperBound="-1"
        eType="#//Implementation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocalternatives" upperBound="-1"
        eType="#//AllocAlternative"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//DescribedClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implementation" eSuperTypes="#//DescribedClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fData" eType="#//FData"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludeFromOptimization"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="system" upperBound="-1"
        eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="h_BlockType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputDeviations" eType="#//OutputDeviations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicEvents" eType="#//BasicEvents"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputDeviation" eSuperTypes="#//NamedClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemOutPort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputDeviations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputDeviation" upperBound="-1"
        eType="#//OutputDeviation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicEvent" eSuperTypes="#//DescribedClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicEvents">
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicEvent" upperBound="-1"
        eType="#//BasicEvent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" eSuperTypes="#//DescribedClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connections" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescribedClass" eSuperTypes="#//NamedClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocAlternative">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hazard" eSuperTypes="#//DescribedClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="safetyRequirement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
